In [1]:
import tensorflow as tf
import numpy as np

# Define the 5x5 input matrix
input_matrix = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 1],
    [1, 2, 1, 0, 0],
    [2, 1, 0, 1, 2],
    [1, 2, 3, 2, 1]
], dtype=np.float32)

# Reshape to match TF input shape: [batch, height, width, channels]
input_tensor = tf.reshape(input_matrix, [1, 5, 5, 1])

# Define the 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=np.float32)

# Reshape to match TF kernel shape: [filter_height, filter_width, in_channels, out_channels]
kernel_tensor = tf.reshape(kernel, [3, 3, 1, 1])

# Function to perform convolution with specified stride and padding
def perform_convolution(stride, padding):
    return tf.nn.conv2d(input_tensor, kernel_tensor, strides=[1, stride, stride, 1], padding=padding)

# Perform convolutions
output_valid_1 = perform_convolution(1, 'VALID')
output_same_1 = perform_convolution(1, 'SAME')
output_valid_2 = perform_convolution(2, 'VALID')
output_same_2 = perform_convolution(2, 'SAME')

# Print results
print("Stride = 1, Padding = 'VALID'\n", output_valid_1.numpy().squeeze())
print("\nStride = 1, Padding = 'SAME'\n", output_same_1.numpy().squeeze())
print("\nStride = 2, Padding = 'VALID'\n", output_valid_2.numpy().squeeze())
print("\nStride = 2, Padding = 'SAME'\n", output_same_2.numpy().squeeze())


Stride = 1, Padding = 'VALID'
 [[-4.  2.  4.]
 [ 0.  0.  0.]
 [ 0.  2.  1.]]

Stride = 1, Padding = 'SAME'
 [[-3. -4.  0.  3.  3.]
 [-5. -4.  2.  4.  3.]
 [-4.  0.  0.  0.  4.]
 [-5.  0.  2.  1.  3.]
 [-3.  0.  0.  0.  3.]]

Stride = 2, Padding = 'VALID'
 [[-4.  4.]
 [ 0.  1.]]

Stride = 2, Padding = 'SAME'
 [[-3.  0.  3.]
 [-4.  0.  4.]
 [-3.  0.  3.]]
